try {
  console.log(a);
} catch (err) {
  console.log("Catch Block");
  console.log(err);
}
